seed: 0
detect_anomaly: false
test_iterations: []
checkpoint_iterations: []

smpl_pkl_path: /mounted/media/dsvitov/DATA/Datasets_avatars/models_smplx_v1_1/models/smplx/SMPLX_NEUTRAL.npz

background: [0., 0., 0.]
random_background: true

# dataset
train_cam_ids: [6, 7, 20, 21, 22, 23, 36, 37, 38, 39, 54, 55, 51, 67, 75, 78, 79, 92, 93, 94, 95, 110, 111, 121, 123, 124, 125, 126, 127, 130, 131, 133, 134, 135, 138, 139, 141, 142, 143, 146, 147, 149, 150, 151, 154, 155, 157, 158, 159]
num_train_frame: 2000
begin_ith_frame: 65
frame_interval: 1
image_scaling: 0.25
max_upscaling: 2.0
data_in_memory: false

test:
  cam_ids: [121] #4 #6
  num_frame:  500 #378 # 1
  begin_ith_frame: 0 #2065 #628 #1064
  frame_interval: 1
  image_scaling: 1
  zoom_in: True
  zoom_out: False
  x_offset: 100
  y_offset: 0
  random_rescaling: false

# optimization
iterations: 400_000
position_lr: 0.00016
opacity_lr: 0.0005
scaling_lr: 0.0005
rotation_lr: 0.0005
color_lr: 0.001
xyz_offset_lr: 0.001
encoder_lr: 0.0005
texture_color_lr: 0.00005
texture_alpha_lr: 0.00005

texture_start: 5000
texture_stop: 380_000
iteration_sh_degree: 100_000

# loss
lambda_lpips: 0.1
iteration_lpips: 6000
iteration_lpips_random_patch: 200_000
lambda_scaling: 0.1
scaling_threshold: 0.01
lambda_dxyz_smooth: 0.1
lambda_normal: 0.05
lambda_dist: 100.0
lambda_texture_value: 0.0001
lambda_alpha_value: 0.0001
max_impact_threshold: 100

init_num_gs: 20_000

# anchor points and control points
num_verts: 10000
num_features: 300

# iteration to start optimize the basis
iteration_dxyz_basis: 2000
iteration_gsparam_basis: 2000
